### ISSUE TITLE
This hostnames break when used with vagrant-hostmanager.

### ISSUE THREAD

**Issue by purpleidea** [vagrant-libvirt/vagrant-libvirt#215]
I'm not entirely sure who's fault this is, if it's vagrant-libvirt or this plugin, but whatever the case, if someone can help me understand why / how this happens, and point me in the right direction, then I'll patch it.

More details:

https://github.com/smdahlen/vagrant-hostmanager/issues/107

Cheers,
James

**Comment by mconigliaro** [comment]
I used to work with @bradleyd and @nicot, and I think I can sum up what's happening here. Imagine you have two separate projects with similar `.kitchen.yml` files:

```yaml
platforms:
- name: centos-6
- name: centos-7

suites:
- name: default
  run_list:
  - recipe[foo::default]
- name: server
  run_list:
  - recipe[foo::server]
```

In Test Kitchen, the VM name is constructed by concatenating the platform and suite names. So for the example above, you'd have the following VM names:

- centos-6-default
- centos-6-server
- centos-7-default
- centos-7-server

Since the cookbook name doesn't appear anywhere in the VM name, it's very likely that you'll end up with conflicts (hence, the reason for the random string added to the end). For what it's worth, Vagrant's default driver (for VirtualBox) solves this problem exactly the same way, though I believe they only use the timestamp with milliseconds.
